<?php echo $this->headTitle('Edição de Tarefas') ?> 
<h2>Editar Tarefa</h3>
<div>           
    <form method="post" >   
        <table class="table table-bordered table-striped">
            <tr>
                <th>Task</th>
                <th>Titulo</th>
                <th>Descrição</th>
                <th>Prioridade</th>                
                <th>Status</th>
                <th>Data Modificação</th>        
                <th>EDITAR</th>
                <th>EXCLUIR</th>
            </tr>
            <tr>
                <td><?php echo $f->getId(); ?></td>
                <td><div class="form-group"><input class="form-control" type="text" name="title" value="<?php echo $this->f->getTitle(); ?>"></div></td>
                <td><div class="form-group"><textarea  class="form-control" type="text" name="description" value=""><?php echo $this->f->getDescription(); ?></textarea></div></td>
                <td><div align="center" class="form-group"><select class="form-control" name="priority" value="<?php echo $this->f->getPriority(); ?>"> <option value="3">Baixa</option>
  <option value="2">Média</option><option value="1">Alta</option></select></div></td>                
                <td><div align="center" class="form-group"><select class="form-control" name="completed" value="<?php echo $this->f->getCompleted(); ?>"> <option value="0">Não concluído</option>
  <option value="1">Concluído</option></select></div>  </td>
                <td><?php echo date_format($f->getCreated(), 'd/m/Y H:i:s'); ?></td>
                <td>
                </td>
                <td>
                    <a href="<?php
                    echo $this->url('rota2', array(
                        'action' => 'excluir', 'id' => $f->getId()
                    ));
                    ?>">
                        <span class="glyphicon glyphicon glyphicon-remove"></span>
                    </a>
                </td>
            </tr>
        </table> 
        <br><br>
        <table>
            <tr>
                <td><input class="btn btn-success pull-left" type="submit" value="Salvar"> </td>
                <td><p><a class="btn btn-primary pull-left" href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'index'));
            ?>">Listar Tarefas</a></p></td>
            </tr>
        </table>
        <br>
    </form>
</div>